name: Publish GPR Package

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup git user
        run: |
          git config user.email "<>"
          git config user.name "${GITHUB_ACTOR}"
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@expressjs'
      - name: NPM Install
        run: npm i
      - name: NPM Version
        run: npm version prerelease --preid="${GITHUB_SHA}"
      - name: NPM Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
      - name: Push version and tag
        run: |
          git push https://wesleytodd:${{secrets.GH_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git --tags
